### ISSUE TITLE
Motion_energy.h

### ISSUE THREAD

**Issue by lwy-599** [UCI-CARL/MotionEnergy#16]
motion_energy.h: No such file or directory.how to solve it?

**Comment by mbeyeler** [comment]
I need a little more info to help you... The file is in /cppME/cppME/inc. On Unix you should go into /cppME/ and run make, then the file will be found. Or which platform are you on?

**Comment by lwy-599** [comment]
PLATFORM:ubuntu CARLsim6
Tutorial/5_motion_energy&nbsp; &nbsp;still can't find motion_energy.h.
cppMe has successfully run.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Michael ***@***.***&gt;; 
发送时间: 2022年6月13日(星期一) 凌晨1:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [UCI-CARL/MotionEnergy] Motion_energy.h (Issue #16)



I need a little more info to help you... The file is in /cppME/cppME/inc. On Unix you should go into /cppME/ and run make, then the file will be found. Or which platform are you on?

**Comment by mbeyeler** [comment]
Oh, I see. This is the standalone ME package. If you're using CARLsim6, I suggest you post there (https://github.com/UCI-CARL/CARLsim6/issues) and maybe Kexin can help you
